
### Successful Login
POST http://localhost:8080/security/authenticate
Content-Type: application/json

{
  "username": "john@smith.com",
  "password": "P@ssw0rd!"
}

### Unsuccessful Login (Invalid Credentials)
POST http://localhost:8080/security/authenticate
Content-Type: application/json

{
  "username": "john@smith.com",
  "password": "wrongpassword"
}

### Test Access to Protected Resource (Using JWT Token)
GET http://localhost:8080/protected/resource
Authorization: Bearer 

### Accessing Protected Resource without Token
GET http://localhost:8080/protected/resource